### ISSUE TITLE
`maxLen` doesn't work as expected.

### ISSUE THREAD

**Issue by christopher-buss** [u3u/eslint-plugin-arrow-return-style#90]
I have `maxLen` set to 80, but when I do:
```ts
const UDimTemporary = (value: UDim, rem: number): UDim => new UDim(value.Scale, value.Offset * rem);
```

Despite being 101 lines long, it does not turn into an explicit export The rule works in the case of the contents of the arrow function itself being 80 lines. Is this intentional?

To me I would like the rule to support line length over content length, as I can still end up with multi-line statements which is what I'd like to avoid, e.g.
```ts
	UDimTemporary11111111111: (value: UDim, rem: number): UDim =>
		new UDim(value.Scale, value.Offset * rem),
```

**Comment by u3u** [comment]
Yes, I only checked the length of the content because the function definition and the function body are two different parts, for example, the content body may be on the next line. I think I might add an option to detect based on the complete function length, but I need to try this first to see if it is feasible.

**Comment by u3u** [comment]
Please upgrade to https://github.com/u3u/eslint-plugin-arrow-return-style/releases/tag/v1.3.1 and give it a try.

**Comment by christopher-buss** [comment]
This seems to work as I wanted! Thank you:)
